services:
    isaac-last-stand:
        build:
            context: .
            target: build
        container_name: isaac-last-stand-back
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379
        command: npm run start:dev -- --host

    redis:
        image: 'redis:alpine'
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data

volumes:
    redis-data:
